/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eoss.spacecraft;

import java.io.Serializable;

/**
 *
 * @author nozomihitomi
 */
public abstract class AbstractBusComponent implements BusComponent, Serializable{
    private static final long serialVersionUID = -8400186424954519993L;
    
    /**
     * The mass of the subsystem
     */
    private final double mass;
    
    /**
     * the power [W] used or generated by the subsystem. Positive numbers
     * indicate power generated, negative numbers indicate power is consumed
     */
    private final double power;

    /**
     * Creates an instance of a bus component
     * @param mass The mass of the subsystem
     * @param power the power used or generated by the subsystem. Positive numbers
     * indicate power generated, negative numbers indicate power is consumed
     */
    public AbstractBusComponent(double mass, double power) {
        this.mass = mass;
        this.power = power;
    }
    
    /**
     * {@inheritDoc}
     * @return 
     */
    @Override
    public double getMass() {
        return mass;
    }
    
    /**
     * {@inheritDoc}
     * @return 
     */
    @Override
    public double getPower() {
        return power;
    }
    
}
